[project]
name = "richat-test"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.5",
    "psycopg2>=2.9.10",
    "python-dotenv>=1.1.1",
    "stripe>=12.4.0",
    "uvicorn[standard]>=0.22.0"
]
